server:
  port: 9170

spring:
  application:
    name: Boss-Server-System
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: BossHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: 16250
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/boss-rbac?useUnicode=ture&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=ture&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      p6spy: true

mybatis-plus:
  type-aliases-package: com.boss.common.entity.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: http://boss:16250@localhost:9001/register/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:9370/auth/user

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true
