FROM openjdk:8u212-jre
MAINTAINER DevinJoe 123@qq.com
COPY boss-server-system-1.0-SNAPSHOT.jar /boss/boss-server-system-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/boss/boss-server-system-1.0-SNAPSHOT.jar"]
