server:
  port: 9370

spring:
  application:
    name: Boos-Gateway

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://boss:16250@localhost:9001/register/eureka/

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: Boss-Auth
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: Boss-Server-System
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: Boss-Server-Test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true

ribbon:
  ReadTimeout: 3000