server:
  port: 9370

spring:
  application:
    name: Boss-Gateay
  boot:
    admin:
      client:
        url: http://${boss-monitor-admin}:9470
        username: boss
        password: 16250
  cloud:
    gateway:
      routes:
        - id: Boss-Auth
          uri: lb://Boss-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/Boss-Auth
        - id: Boss-Server-System
          uri: lb://Boss-Server-System
          predicates:
            - Path=/system/**
          filters:
              - name: Hystrix
                args:
                  name: systemfallback
                  fallbackUri: forward:/fallback/Boss-Server-System
        - id: Boss-Server-Test
          uri: lb://Boss-Server-Test
          predicates:
            - Path=/test/**
          filters:
              - name: Hystrix
                args:
                  name: testfallback
                  fallbackUri: forward:/fallback/Boss-Server-Test
      default-filters:
        - StripPrefix=1

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: http://boss:16250@${boss-register}:9001/register/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,gateway

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000