server:
  port: 9470


spring:
  application:
    name: Boss-Monitor-Admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  security:
    user:
      name: boss
      password: 16250
